FROM evoapicloud/evolution-api:v2.3.7
ENV PORT=8080
ENV SERVER_PORT=8080
ENV DATABASE_ENABLED=true
ENV DATABASE_PROVIDER=postgresql
ENV CACHE_REDIS_ENABLED=false
ENV CACHE_LOCAL_ENABLED=true
EXPOSE 8080
